CREATE TABLE IF NOT EXISTS users (
	user_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	user_login TEXT NOT NULL,
	user_password TEXT NOT NULL,
	user_email TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS notes (
	note_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	user_id INTEGER NOT NULL,
	note_private INTEGER NOT NULL,
	note_title TEXT NOT NULL,
	note_text TEXT NOT NULL
);